export enum IGameActions {
    HANDLE_QUESTION_ANSWERED_WRONG = 'HANDLE_QUESTION_ANSWERED_WRONG',
    CHANGE_ACTIVE_TIP = 'CHANGE_ACTIVE_TIP',
    HANDLE_CLICK_ON_TIP_OPTION = 'HANDLE_CLICK_ON_TIP_OPTION',
    SETUP_NEXT_CARD = 'SETUP_NEXT_CARD',
    CHANGE_PAGE = 'CHANGE_PAGE',
    FILTER_CARDS = 'FILTER_CARDS',
    SET_LOADING = 'SET_LOADING',
    SET_SHOW_CARD_STATS = 'SET_SHOW_CARD_STATS',
    SET_SOUND_DATA = 'SET_SOUND_DATA',
    SET_SELECTED_CATEGORIES = 'SET_SELECTED_CATEGORIES',
}
