export enum IGameActions {
    HANDLE_QUESTION_ANSWERED_WRONG = 'HANDLE_QUESTION_ANSWERED_WRONG',
    CHANGE_ACTIVE_TIP = 'CHANGE_ACTIVE_TIP',
    HANDLE_CLICK_ON_GUESS_OPTION = 'HANDLE_CLICK_ON_GUESS_OPTION',
    SETUP_NEXT_CARD = 'SETUP_NEXT_CARD',
    CHANGE_PAGE = 'CHANGE_PAGE',
}
